// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wallets.Persistence.Context;

#nullable disable

namespace Wallets.Persistence.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wallets.Domain.Models.Commission", b =>
                {
                    b.Property<Guid>("EventExternalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserExternalId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SchemaType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("EventExternalId", "UserExternalId");

                    b.HasIndex("UserExternalId");

                    b.HasIndex("EventExternalId", "Level")
                        .IsUnique();

                    b.ToTable("commissions", (string)null);
                });

            modelBuilder.Entity("Wallets.Domain.Models.Wallet", b =>
                {
                    b.Property<Guid>("UserExternalId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("SchemaType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("UserExternalId");

                    b.ToTable("wallets", (string)null);
                });

            modelBuilder.Entity("Wallets.Domain.Models.Commission", b =>
                {
                    b.HasOne("Wallets.Domain.Models.Wallet", "Wallet")
                        .WithMany("Commissions")
                        .HasForeignKey("UserExternalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Wallets.Domain.Models.Wallet", b =>
                {
                    b.Navigation("Commissions");
                });
#pragma warning restore 612, 618
        }
    }
}
