// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Users.Persistence.Context;

#nullable disable

namespace Users.Persistence.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20260922201412_AddOutbox")]
    partial class AddOutbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Users.Domain.Models.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAtUtc", "AttemptCount", "CreatedAtUtc");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Users.Domain.Models.PartnerRelation", b =>
                {
                    b.Property<Guid>("UserExternalId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<Guid>("PartnerExternalId")
                        .HasColumnType("uuid");

                    b.HasKey("UserExternalId", "Level");

                    b.HasIndex("PartnerExternalId");

                    b.HasIndex("UserExternalId", "PartnerExternalId")
                        .IsUnique();

                    b.ToTable("partner_relations", (string)null);
                });

            modelBuilder.Entity("Users.Domain.Models.User", b =>
                {
                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("ExternalId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Users.Domain.Models.PartnerRelation", b =>
                {
                    b.HasOne("Users.Domain.Models.User", "PartnerUser")
                        .WithMany()
                        .HasForeignKey("PartnerExternalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Users.Domain.Models.User", "User")
                        .WithMany("PartnerRelations")
                        .HasForeignKey("UserExternalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartnerUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Users.Domain.Models.User", b =>
                {
                    b.Navigation("PartnerRelations");
                });
#pragma warning restore 612, 618
        }
    }
}
